global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "as44"
    scheme: https
    scrape_interval: 15s
    static_configs:
      - targets: ["host.docker.internal:8080"]
    tls_config:
      insecure_skip_verify: true
